### ISSUE TITLE
Visualizations of the results

### ISSUE THREAD

**Issue by answerrtx** [wisdomikezogwo/quilt1m#14]
Hello, thank you for your great work! 

I see that in this repository, there are comparisons in terms of visualization. Could you provide the visualization tutorials or scipt on this? Thank you!

**Comment by wisdomikezogwo** [comment]
Hi, 

We leveraged standard matplotlib pyplot for the visualizations based on the results dict to generate the plots, and unfortunately this was done on a notebook file that has since been deleted, so you'd have to leverage pyplot's documentation. I hope this helps.
