### ISSUE TITLE
Image-to-text generation

### ISSUE THREAD

**Issue by anabiasuhail** [wisdomikezogwo/quilt1m#17]
Can you please guide, How I can use quilt1 for image to text generation. Like I input an image, and it generates the text. Do I need to use LLaVA and BLIP like modes where I assign the weights of the quilt1m and use it for text description generation. As the API mentioned at the hugging face is only for zero short classification. and I could not find the Text retrieval code in GitHub repo. Moreover, I also tried blip, but got compatibility issues. Thanks.

**Comment by wisdomikezogwo** [comment]
Hi, 

To use QuiltNet for retrieval, I'd suggest you use https://github.com/LAION-AI/CLIP_benchmark, which we also leveraged in the evaluation.

Also for Text-generation tasks we recently released a new work called [Quilt-LLAVA](https://quilt-llava.github.io/) where we essentially use the image tower of Quiltnet in training Quilt-LLAVA. Fortunately, The model should be either tonight or tomorrow night. With that Quilt-LLAVA, you could conduct research with an LMM tuned for histopathology. Please [read the paper](https://arxiv.org/abs/2312.04746) when you have some time.
