### ISSUE TITLE
Error on loading QuiltNet-B-16

### ISSUE THREAD

**Issue by SongDoHou** [wisdomikezogwo/quilt1m#20]
Hi, 
The error is occurred from below command:

`from transformers import CLIPModel`
`model = CLIPModel.from_pretrained("wisdomik/QuiltNet-B-16", use_auth_token=None)` .

The error msg is:
```
RuntimeError: Error(s) in loading state_dict for CLIPModel:
	size mismatch for vision_model.embeddings.patch_embedding.weight: copying a param with shape torch.Size([768, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([768, 3, 32, 32]).
	size mismatch for vision_model.embeddings.position_embedding.weight: copying a param with shape torch.Size([197, 768]) from checkpoint, the shape in current model is torch.Size([50, 768]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

Is there any issues with that? or my dev environment has something wrong?

**Comment by wisdomikezogwo** [comment]
Hi, try to use this:

```
import open_clip

model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms('hf-hub:wisdomik/QuiltNet-B-16')
tokenizer = open_clip.get_tokenizer('hf-hub:wisdomik/QuiltNet-B-16')
```

**Comment by byte-dance** [comment]
I wonder 'pytorch_model.bin' and 'open_clip_pytorch_model.bin' which one is the right bin that you trainen yourself?

**Comment by wisdomikezogwo** [comment]
Training outputs open_clip_pytorch_model.bin and we convert it to pytorch_model.bin also for compatibility with loading the models directly using HF CLIP modules and not just open_clip. So both are the same and trained as discussed in the paper.
