### ISSUE TITLE
Downstream tasks setting

### ISSUE THREAD

**Issue by cheliu-computation** [wisdomikezogwo/quilt1m#3]
First thansk for your impressive work on meidcal VLP coummunity!

From your paper, there are many downstream tasks in the benchmark to evlaute the VLP model, could you provide the pipeline or script to prepare the downstream dataset and evaluation?

Best Regards

**Comment by wisdomikezogwo** [comment]
Thanks for your comments!

Added a few pointers on how to curate the datasets and evaluate QuiltNet on them in /eval/README.md. With time I'll update the ReadMe to include some of the data links directly, however, all the links are easily searchable and all the datasets are easily obtainable, so it shouldn't be a hassle parsing them, if you do have any issues worth so ever please let us know. 

Again thanks.

**Comment by cheliu-computation** [comment]
Thanks a lot!

Now the dataset preparation is built on the csv and video downloading, will you upload the whole image-text dataset to huggingface or other place with raw image format rather than video?

**Comment by wisdomikezogwo** [comment]
We belive that violates Youtube policies, and so we employ you to leverage open-source packages to download said videos and follow the steps outlined in the readme to parse those videos into images and save them -- i.e reconstruct Quilt!

Hope this is helpful, if you have any other questions, I'm happy to help.

**Comment by cheliu-computation** [comment]
Thanks a lot!
