### ISSUE TITLE
Missing Imports and Code Errors

### ISSUE THREAD

**Issue by vinid** [wisdomikezogwo/quilt1m#5]
Hello!

Thanks for the great resource!

I have been trying to run the data reconstruction but I kind of stumbled upon a couple of different errors (some are missing imports - e.g., nn from torch - one was a parenthesis that was not closed). There are also a couple of missing requirements (e.g., scikit-image) in the requirements file.

Would you mind taking a look? I have solved some of these and I am happy to send a PR in case but maybe you have an updated version of the code that runs out of the box.

**Comment by wisdomikezogwo** [comment]
Hi, 

Thanks for trying to reconstruct Quilt!

Went ahead and made the code changes and fixed the imports. Also, noticed scikit-image is already in the requirements file so not sure why it's an issue, it may be that the particular version is off and so was not installed, I went ahead and removed the version tag just in case as it should not affect anything.

Finally, please let me know if there are any more issues.

**Comment by vinid** [comment]
thank you so much for the prompt reply! Trying this now!

**Comment by vinid** [comment]
The instruction specifies that the CSVs should be put in  `${BASE_DIR}/videos/...`.

However, I see the code is as follows:
`recon_df = pd.read_csv(os.path.join(BASE_DIR, 'quilt_recon.csv'))`

I solved the error by moving both CSVs to `BASE_DIR` but might be worth updating this.

Currently getting this error:

```bash

(base) [fede] $ python main.py --base_dir ${BASE_DIR}
Please use the `--pretrained_weights` argument to indicate the path of the checkpoint to evaluate.
Since no pretrained weights have been provided, we load the reference pretrained DINO weights.
Take key state_dict in provided checkpoint dict
Pretrained weights found at /oak/stanford/groups/jamesz/pathtweets/quilt/quilt1m/histo_models/dino_checkpoint.pth.tar and loaded with msg: <All keys matched successfully>
Traceback (most recent call last):
  File "/oak/stanford/groups/jamesz/pathtweets/quilt/quilt1m/data/main.py", line 161, in <module>
    main(args, data_df, recon_df, device, histo_models_dict, video_paths_dict)
  File "/oak/stanford/groups/jamesz/pathtweets/quilt/quilt1m/data/main.py", line 48, in main
    video_path = video_paths_dict[vid_id]
KeyError: '8G7VgvBQWIA'
```

Is there anything specific I might be doing wrong? Thank you so much for your help!

**Comment by vinid** [comment]
my bad. it's probably an error on my side, let me check!
