### ISSUE TITLE
Downloaded Dataset Size

### ISSUE THREAD

**Issue by eemokey** [wisdomikezogwo/quilt1m#8]
Hi!

- What is the expected size of the dataset once downloaded? After processing by calling main.py? 
- Also approximately how long would each step of the process take?

**Comment by wisdomikezogwo** [comment]
Hi,

1) After compression the size of the images (extracted at the highest frame resolution for each video) should be ~60GB
2) Unfortunately we haven't benchmarked how long it takes to run this on all videos, but if the initial process is anything to go by, it might take a while to compute with the scene extractions (on CPU) being the bottleneck, I'd say my best estimate would be a 400hrs on a single CPU+GPU node however with chunking this can be reduced even more.

I hope this answers your question, do let us know if you have any more.

**Comment by eemokey** [comment]
That's great! Thank you!
