### ISSUE TITLE
Providing dataset

### ISSUE THREAD

**Issue by qkrtnskfk23** [wisdomikezogwo/quilt1m#9]
First of all, thank you for providing good paper and dataset.

I am wondering whether your team have a plan to provide quilt-1m dataset including additional dataset from twitter, PMC, etc.

Thank you!

**Comment by wisdomikezogwo** [comment]
Thank you for your question. We are actually finalizing restricted access to the entire dataset, and anyone should be able to access the data after a request soon, hopefully, in a few days that will be made available!

**Comment by qkrtnskfk23** [comment]
Thank you for your answer!! I am looking forward to opening the quilt-1m dataset!
